### ISSUE TITLE
French Translation ?

### ISSUE THREAD

**Issue by onelots** [jellyfish-dev/book#4]
Hi, are you planning to translate it in french ? Or would you be interested by a french Translation ?

**Comment by mickel8** [comment]
Hi @Oneloutre!

At the moment, we are not going to translate the book in other languages. There are a couple of reasons:
* it's too early, we have just started and we haven't written too many chapters yet
* we won't be able to maintain other languages on our own
* the book is not so popular yet

However, it would be awesome to rethink this idea in some time :slightly_smiling_face:
